name: navigation_2_restaurant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  http: ^1.2.2
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
